=== Arosmor/AmoRos_ExUD4_LMSGT/Ejercicio1/LosRemediosSA.dtd
<!ELEMENT losremediossa (pedido)>
<!ELEMENT pedido (sucursal,cod_sucursal,nombre_trabajador,fecha_pedido,observaciones,articulos)>
<!ELEMENT sucursal (#PCDATA)>
<!ELEMENT cod_sucursal (#PCDATA)>
<!ELEMENT nombre_trabajador (#PCDATA)>
<!ELEMENT fecha_pedido (#PCDATA)>
<!ELEMENT observaciones (#PCDATA)>
<!ELEMENT articulos (articulo)>
<!ELEMENT articulo (cod_articulo,unidades,precio_unidad,observaciones_articulo,plazo_revision)>
<!ELEMENT cod_articulo (#PCDATA)>
<!ELEMENT unidades (#PCDATA)>
<!ELEMENT precio_unidad (#PCDATA)>
<!ELEMENT observaciones_articulo (#PCDATA)>
<!ELEMENT plazo_revision (#PCDATA)>

=== Arosmor/AmoRos_ExUD4_LMSGT/Ejercicio1/LosRemediosSA_D.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE losremediossa SYSTEM "LosRemediosSA.dtd">
<losremediossa>
    <pedido>
        <sucursal> Ubrique </sucursal>
        <cod_sucursal>F8456975</cod_sucursal>
        <nombre_trabajador>Amos</nombre_trabajador>
        <fecha_pedido>13/02/2022</fecha_pedido>
        <observaciones>-</observaciones>
        <articulos>
            <articulo>
                <cod_articulo>EER-568</cod_articulo>
                <unidades>2</unidades>
                <precio_unidad>12€</precio_unidad>
                <observaciones_articulo>-</observaciones_articulo>
                <plazo_revision>24€</plazo_revision>
            </articulo>
        </articulos>
    </pedido>
</losremediossa>
